const GET_PLANET_START = 'GET_PLANET_START';
const GET_PLANET_SUCCESS = 'GET_PLANET_SUCCESS';
const GET_PLANET_ERROR = 'GET_PLANET_ERROR';
const CLEAR_PLANET_DATA = 'CLEAR_PLANET_DATA';

const GET_PLANETS_START = 'GET_PLANETS_START';
const GET_PLANETS_SUCCESS = 'GET_PLANETS_SUCCESS';
const GET_PLANETS_ERROR = 'GET_PLANETS_ERROR';

const GET_NEXT_PLANETS_START = 'GET_NEXT_PLANETS_START';
const GET_NEXT_PLANETS_SUCCESS = 'GET_NEXT_PLANETS_SUCCESS';
const GET_NEXT_PLANETS_ERROR = 'GET_NEXT_PLANETS_ERROR';

const GET_RESIDENT_START = 'GET_RESIDENT_START';
const GET_RESIDENT_SUCCESS = 'GET_RESIDENT_SUCCESS';
const GET_RESIDENT_ERROR = 'GET_RESIDENT_ERROR';
const CLEAR_RESIDENT_DATA = 'CLEAR_RESIDENT_DATA';

const GET_RESIDENTS_START = 'GET_RESIDENTS_START';
const GET_RESIDENTS_SUCCESS = 'GET_RESIDENTS_SUCCESS';
const GET_RESIDENTS_ERROR = 'GET_RESIDENTS_ERROR';
const CLEAR_RESIDENTS_DATA = 'CLEAR_RESIDENTS_DATA';

export const actionTypes = {
  GET_PLANET_START,
  GET_PLANET_SUCCESS,
  GET_PLANET_ERROR,
  CLEAR_PLANET_DATA,

  GET_PLANETS_START,
  GET_PLANETS_SUCCESS,
  GET_PLANETS_ERROR,

  GET_NEXT_PLANETS_START,
  GET_NEXT_PLANETS_SUCCESS,
  GET_NEXT_PLANETS_ERROR,

  GET_RESIDENT_START,
  GET_RESIDENT_SUCCESS,
  GET_RESIDENT_ERROR,
  CLEAR_RESIDENT_DATA,

  GET_RESIDENTS_START,
  GET_RESIDENTS_SUCCESS,
  GET_RESIDENTS_ERROR,
  CLEAR_RESIDENTS_DATA,
};
